---
title: "JTK_num_cyclers_vs_signif_cutoff"
format: html
editor: visual
---

This file is for generating the plot in figure 1 with the #cyclers vs signif cutoff

```{r}
library(tidyverse)
library(gridExtra)
```

```{r}
setwd("Core_clock_face_python_plots/")


get_num_genes_helper = function(df, threshold, amp_ratio_cutoff = 0.){
  df = filter(df, ampRatio > amp_ratio_cutoff)
  df = df[order(df$BH.Q),]
  df$num_genes = seq_along(df$BH.Q)  # Create a cumulative count column
  df = df %>% mutate(log10BHQ = -log10(BH.Q))
  results = dplyr::select(df, log10BHQ, num_genes)
  rm_above = which(results$log10BHQ == 0) %>% head(1) #last gene w p == 1
  results = results[-((rm_above+1):nrow(results)), ]
  return(results)
}
get_num_genes = function(filename){
  file = read_csv(filename, show_col_types = F)
  file$mean = rowMeans(file[,-c(1:6)])
  file$ampRatio = file$AMP/file$mean
  results = get_num_genes_helper(file, amp_ratio_cutoff = 0.)
  
}

WT_bulk = get_num_genes("JTKresult_bulk_WT_data.csv")
WT_astro = get_num_genes("JTKresult_astro_wt_data.csv")
WT_mglia = get_num_genes("JTKresult_micro_WT_data.csv")
APP_bulk = get_num_genes("JTKresult_bulk_APP_data.csv")
APP_astro = get_num_genes("JTKresult_astro_APP_data.csv")
APP_mglia = get_num_genes("JTKresult_micro_APP_data.csv")


p1= ggplot() +
  geom_line(data = WT_bulk, aes(x = log10BHQ,
                                y = num_genes, color = "Bulk")) +
  geom_line(data = WT_mglia, aes(x = log10BHQ, y = num_genes, color = "Microglia")) +
  geom_line(data = WT_astro, aes(x = log10BHQ, y = num_genes, color = "Astrocyte")) +
  labs(x = "-Log10(JTK BH.Q)", y = "Number of Cycling Transcripts") +
  scale_color_manual(name = "Cell Type", values = c("Bulk" = "darkgreen", "Microglia" = "darkred", "Astrocyte" = "blue")) +
  theme_minimal()+
  ylim(c(0, 10000))+
  xlim(c(0, 3))
p2= ggplot() +
  geom_line(data = APP_bulk, aes(x = log10BHQ,
                                y = num_genes, color = "Bulk")) +
  geom_line(data = APP_mglia,  aes(x = log10BHQ, y = num_genes, color = "Microglia")) +
  geom_line(data = APP_astro, aes(x = log10BHQ, y = num_genes, color = "Astrocyte")) +
  labs(x = "-Log10(JTK BH.Q)", y = "Number of Cycling Transcripts") +
  scale_color_manual(name = "Cell Type", values = c("Bulk" = "darkgreen", "Microglia" = "darkred", "Astrocyte" = "blue")) +
  theme_minimal()+
  ylim(c(0, 5000))+
  xlim(c(0, 3))


grid.arrange(p1, p2, nrow = 1)
```
