---
title: "MetaboAnalyst_custom_plot"
format: html
editor: visual
---

This file is for taking the MetaboAnalyst results and making pretty plots from them.

### Read in the metaboAnalyst Results:

```{r}
library(tidyverse)
library(ggrepel)
pathway_res_CTL = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/Cycling_in_CTL_PseudobulkAR20Genes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv", show_col_types = F)

pathway_res_AD = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/Cycling_in_AD_PseudoBulkAR20Genes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv", show_col_types = F)

pathway_res_Diff_Rhyth = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/DR_p05_PseudobulkAR20Genes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv", show_col_types = F)

pathway_res_Diff_Rhyth_Lose_Rhythm = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/DR_p05_LOSEAMP_PseudobulkAR20LoseAmpGenes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv", show_col_types = F)

pathway_res_Diff_Rhyth_Gain_Rhythm = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/DR_p05_GAINAMP_PseudobulkAR20GainAmpGenes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv")
```

Make the Plots:

```{r}
ggplot(pathway_res_CTL, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "#0091ff", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 10)+
   theme_minimal()
```

```{r}
ggplot(pathway_res_AD, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "red", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 8)+
   theme_minimal()
```

```{r}
ggplot(pathway_res_Diff_Rhyth, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "orange", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 8)+
   theme_minimal()
```

```{r}
ggplot(pathway_res_Diff_Rhyth_Gain_Rhythm, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "green", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 5)+
   theme_minimal()
```

```{r}
ggplot(pathway_res_Diff_Rhyth_Lose_Rhythm, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "brown", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 5)+
   theme_minimal()
```
